# Generated by Django 4.0.5 on 2022-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='category',
            field=models.ManyToManyField(through='news.SubscriberCategory', to='news.category'),
        ),
    ]
